service: multi-runtime-serverless

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
    noAuth: true

provider:
  name: aws
  region: us-east-1
  environment:
    NODE_ENV: development

functions:
  pythonHello:
    runtime: python3.8
    handler: src/python/handler.hello
    events:
      - http:
          path: python/hello
          method: get

  nodeHello:
    runtime: nodejs20.x
    handler: src/nodejs/handler.hello
    events:
      - http:
          path: nodejs/hello
          method: get
