service: multi-runtime-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    NODE_ENV: production

functions:
  pythonHello:
    handler: handler.hello
    runtime: python3.8
    module: functions/python
    events:
      - http:
          path: python/hello
          method: get

  nodeHello:
    handler: functions/nodejs/handler.hello
    runtime: nodejs14.x
    events:
      - http:
          path: nodejs/hello
          method: get
